### ISSUE TITLE
Is there any simple way (that you recommend) to load this library in the frontend?

### ISSUE THREAD

**Issue by luisArandas** [neuml/txtai.js#15]
Hi!

How would you recommend we use this library in the front-end? If so how would you recommend the instances?

Thanks!

**Comment by davidmezzetti** [comment]
Hello, thank you for the question.

What have you tried so far? It's a module on npm and it connects to a backend URL. Assuming the front-end has access to the URL, things should work. 

With that being said, this library is more intended as a backend Node.js library, so this use case hasn't been tested much.

**Comment by luisArandas** [comment]
Hello @davidmezzetti.

I am working with the main library on Python, just wondering how hard would it be to port what I already have to js. My approach now would be to probably make an API using FastAPI? The only mention I found was here `https://github.com/neuml/txtai/blob/master/examples/08_API_Gallery.ipynb` on `Start an API instance` but I am not sure on how to follow yours steps. 

Is this the right way to go? I think in your examples that gets served then to node. I did install `npm install txtai` but got an error when I try to `const hey = require('txtai')`. I think this is related? 

Thanks

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/luisarandas/github/installations/bma/node_modules/txtai/dist/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

**Comment by davidmezzetti** [comment]
Regarding the error, what happens if you run:

```
npm install --dev
```

You can also connect directly to the API from JavaScript as the Python instance already has a FastAPI service running. That is basically what txtai.js is doing.

**Comment by davidmezzetti** [comment]
Closing due to inactivity. Feel free to re-open or open a new issue if there are further questions.

**Comment by luisArandas** [comment]
Hello @davidmezzetti. I am sorry for the delay. Unfortunately your solution doesn't work. I just created a new project with `npm init`, and `npm install txtai`. When adding `txtai = require('txtai')` I get the error anyway.

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'txtai'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/luisarandas/Desktop/txtai/index.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

**Comment by davidmezzetti** [comment]
I'll try to test this scenario out more. What front-end framework are you running in?

**Comment by luisArandas** [comment]
Hello! I'm so sorry for the late reply. I tried with `npm install --dev` but also didn't work. I'm just using a flask server and display the web files and socketio for communication!
